name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - main  # Runs on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            cd ~/turf/turf_backend
            git pull origin main
            
            # Install Dependencies
            npm install
            
            # Restart Node.js app using PM2 (recommended for production)
            pm2 restart turf_backend || pm2 start server.js --name "turf_backend"
            
            # Check PM2 process status
            pm2 status turf_backend
